#!/bin/bash
# Auto-generated by docrecord on 2025-09-24
# This script automates the steps documented in installgrafana.md

set -e

# Step 1: คำสั่ง ls ใช้แสดงรายการไฟล์และไดเร็กทอรีในระบบไฟล์
ls

# Step 2: คำสั่ง pwd ใช้แสดงเส้นทางไดเร็กทอรีปัจจุบัน
pwd

echo "✅ Automation script completed successfully."
