#!/bin/bash
# Auto-generated by docrecord on 2025-09-24
# This script automates the steps documented in setup-server-2.md

set -e

# Step 1: แสดงรายการไฟล์และไดเร็กทอรี

ls

# Step 2: คำสั่งนี้แสดงรายการไฟล์และไดเร็กทอรีในไดเร็กทอรีปัจจุบัน

สห

# Step 3: แสดงรายการไฟล์และไดเร็กทอรี

ls

echo "✅ Automation script completed successfully."
