#!/bin/bash
# Auto-generated by docrecord on 2025-09-24
# This script automates the steps documented in setup-server.md

set -e

# Step 1: แสดงรายการไฟล์และไดเร็กทอรี

ls

# Step 2: Failed to get AI explanation.
clear

echo "✅ Automation script completed successfully."
